# Generated by Django 5.1.2 on 2024-10-22 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
    ]
