# Generated by Django 5.1.2 on 2024-10-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_add_initial_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='looking_for',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('both', 'Both')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='interests',
            field=models.ManyToManyField(blank=True, to='survey.interest'),
        ),
    ]
